all:
	javac Myset.java
	javac MobilePhone.java
	javac MobilePhoneSet.java
	javac Exchange.java
	javac ExchangeList.java
	javac RoutingMapTree.java
	javac checker.java

run:
	java checker

clean:
	rm *.class
